### ISSUE TITLE
Kabhi Khusi Kabhi Gam title says Ishq

### ISSUE THREAD

**Issue by uchadh** [jungeebah/herekochu#14]

**Comment by uchadh** [comment]
![image](https://user-images.githubusercontent.com/64935237/82132617-c5185a80-97af-11ea-97e9-61b663039f91.jpeg)

**Comment by jungeebah** [comment]
Please look at your code and edit the title section @uchadh .

This is the user issue nothing can be done so closing this issue

**Comment by uchadh** [comment]
We need to fix this. REOPENING this.
